codecov:
  require_ci_to_pass: false
  bot: null

coverage:
  precision: 2
  round: down
  range: "70...90"
  status:
    project:
      default:
        target: 90% #overall project/repo coverage
    patch:
      default:
        target: 90% #branch patch coverage

ignore:
  - "contracts/utils"
